# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Librarian', to=settings.AUTH_USER_MODEL),
        ),
    ]
